app = "your-app-name"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  image = "your-docker-image"  # If using a custom Docker image

[env]
  PORT = "8080"

[services]
  internal_port = 8080
  protocol = "tcp"
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
